dir: rtl
language: ar
remote_theme: daattali/beautiful-jekyll
show_downloads: false
title: خالد
description: حلول تقنية المعلومات
layout: page

# Navbar Links #
navbar-links:
  رابط التحقق: "https://freelance.sa/app/ar/licenses/d45c137b"
  
# Social #
social-network-links:
  email: "khaled.flance@gmail.com"
  telephone: 0555144961
